FORMAT: 1A
HOST: http://onebox-venueaccess-api.getsandbox.com/

# onebox-venueaccess-api

API to manage ticketing white and black lists to let access the venue or deny it.

To do so, we have used a **API Blueprint** standard, **apiary** as an online editing and mocking tool, **aglio** to document it and **getsandbox** as a sandbox provider:
+ [API Blueprint](https://apiblueprint.org/)
+ [apiary.io](http://docs.oneboxvenueaccessapi.apiary.io/)
+ [getsandbox.com](http://onebox-venueaccess-api.getsandbox.com/)
+ [aglio](https://github.com/danielgtaylor/aglio)
+ [github](https://github.com/joliva-ob/onebox-venueaccess-api)
+ [onebox-developer](http://developer.oneboxtickets.com/venueaccess-api/)

## OAuth2 Requests [/oauth/token]

### OAuth2 Request Access Token [POST]

You will need to use OAuth to access the API.  Write to us at api-support@oneboxtm.com.  We will give you a client ID and client secret. Use this as shown in the following call in order to retrieve a token.
Once you have a token you can use it in all API calls as shown below.

+ Request  (application/json)

        {
            "grant_type": "password",
            "client_id": [CLIENT_ID],
            "client_secret": [CLIENT_SECRET],
            "password": [YOURPASSWORD],
            "username": [YOURUSERNAME]
        }

+ Response 201 (application/json)

        {
            "access_token": "[OAUTH2_TOKEN]",
            "token_type":"bearer",
            "expires_in":7200,
            "refresh_token": "[REFRESH_TOKEN]"
        }

+ Response 400 (application/json)

        {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
        }

+ Response 401 (application/json)

        {
          "error": "unauthorized",
          "error_description": "Full authentication is required to access this resource"
        }

## Whitelist tickets collection [/venueaccess-api/v1.0/whitelist/tickets{?id,code,start_date,end_date,event_id,performance_id,page,page_size,status}]
List all the key data from the tickets filtered by the given parameters.

See below the description of the response fields we consider that need to be explained:

| Response Field                   | Description                             |
|----------------------------------|-----------------------------------------|
| version                          | (Text) Version of the API               |
| href                             | (Text) Url of the API doc               |
| trace_id                         | (Text) unique identifier of the request |
| parameters                       | (Object) Request filtering used         |

### List whitelist tickets [GET]

+ Request

  + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Parameters
    + id (optional, number) ... Filter by id
    + code (optional, text) ... Filter by the ticket reference code.
    + start_date (optional, date) ... Filter by starting date (`2015-08-05T08:40:51Z`)
    + end_date (optional, date) ... Filter by final date (`2015-08-05T08:40:51Z`)
    + event_id (optional, text) ... Filter by a given event.
    + performance_id (optional, text) ... Filter by a given event date.
    + page (optional, number) ... Paginate response to the given page number
    + page_size (optional, number) ... Size of the each page requested.
    + status (optional, enum[string])

        Filter by ticket status, available choices are:

        + Members
            + `AVAILABLE` - Indicates that the ticket is ready to be reserved.
            + `RESERVED` - Tickets blocked and ready to be released or confirmed.
            + `CONFIRMED` - Ticket is definetively blocked and ready to be sent.
            + `CANCELLED` - Ticket is marked as non-valid.
            + `SENT` - Ticket is already sended to the venue access control system.

+ Response 200 (application/json)

        {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/venueaccess/v1.0/whitelist/",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "request_date": "2015-08-05T08:40:51Z",
            "channel_id": "int_channel@oneboxtm.com",
            "hits": 2,
            "parameters":
            {
              "id": "",
              "code": "",
              "start_date": "",
              "end_date": "",
              "event_id": "",
              "session_id": "",
              "status": "",
              "page": 2,
              "page_size": 10
            },

            "buyers": [
              {
                "id": "joan@email.com",
                "name": "first name",
                "surname": "last name",
                "birth_date": "1980-05-02",
                "gender": "male",
                "address1": "first line address",
                "address2": "second line address",
                "city": "Pineda de Mar",
                "state": "Barcelona",
                "zip_code": "08397",
                "country": "ES",
                "language": "es_ES",
                "signup_date": "2015-08-05T08:40:51Z",
                "phone": "+34 555 555 555",
                "mobile": "+34 555 555 555",
                "newsletter_agreement": true,
                "sms_agreement": false,
                "phone_agreement": false,
                "post_agreement": true,
                "passbook_generated": false,
                "update_date": "2015-08-05T08:40:51Z"
              },
              {
                "id": "eva@email.com",
                "name": "first name",
                "surname": "last name",
                "birth_date": "1984-12-11",
                "gender": "female",
                "address1": "first line address",
                "address2": "second line address",
                "city": "Pineda de Mar",
                "state": "Barcelona",
                "zip_code": "08397",
                "country": "ES",
                "language": "es_ES",
                "signup_date": "2015-08-05T08:40:51Z",
                "phone": "+34 555 555 555",
                "mobile": "+34 555 555 555",
                "newsletter_agreement": true,
                "sms_agreement": false,
                "phone_agreement": false,
                "post_agreement": true,
                "passbook_generated": false,
                "update_date": "2015-08-05T08:40:51Z"
              }
            ],

            "links": [
              {
                "name": "next_page",
                "prompt": "Next",
                "rel": "next",
                "href": "buyers?page=3",
                "render": "link"
              },
              {
                "name": "previous_page",
                "prompt": "Bext",
                "rel": "back",
                "href": "buyers?page=1",
                "render": "link"
              }
            ]

          }

+ Response 204 (application/json)

+ Response 400 (application/json)

        {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
        }

+ Response 401 (application/json)

        {
          "error": "unauthorized",
          "error_description": "Full authentication is required to access this resource"
        }

## Purchases Collection [/crm-api/v1.0/purchases{?id,buyer_id,start_date,end_date,event_id,session_id,channel_name,page,page_size,status,passbook}]
List all the key data from the purchases including its products, the order details they came from, the orderline and its channel on sale. Finally it is also allowed filtering between dates and paging.

| Response Field                   | Description                                        |
|----------------------------------|----------------------------------------------------|
| version                          | (Text) Version of the API                          |
| href                             | (Text) Url of the API doc                          |
| trace_id                         | (Text) unique identifier of the request            |
| parameters                       | (Object) Request filtering used                    |
| purchases.order.status           | (enum) OK, ERROR, ABANDONED, REFUND, CANCELLED     |
| purchases.order.delivery_method  | (enum) EMAIL, TICKET, BOXOFFICE, EXTERNAL, PASSBOOK|
| purchases.order.products_number  | (Number) Number of tickets from a given order      |

### List All Purchases [GET]

+ Request

  + Headers

            Authorization: Bearer OAUTH2_TOKEN
            Accept: application/json

+ Parameters
    + id (optional, text) ... Filter by a given purchase identified by its Onebox order code
    + buyer_id (optional, text) ... Filter by a given buyer identified by its Onebox user email.
    + start_date (optional, date) ... Filter by starting date (`2015-08-05T08:40:51Z`)
    + end_date (optional, date) ... Filter by final date
    + event_id (optional, text) ... Filter by a given event.
    + session_id (optional, text) ... Filter by a given session.
    + channel_name (optional, text) ... Filter by onsell channel name.
    + page (optional, number) ... Paginate response to the given page number
    + page_size (optional, number) ... Size of the each page requested.
    + status (optional, enum[string])
    + passbook (optional, bool) ... Filter whether passbook has been generated or not.

        Filter by order status, the available choices are:

        + Members
            + `ABANDONED` - Indicates that the shopping cart and its linked order has not been confirmed yet.
            + `OK` - Orders successfully confirmed (purchase).
            + `ERROR` - Orders which have not finalized properly.
            + `REFUND` - Orders with money amount refunded back successfully.
            + `CANCELLED` - Orders cancelled.


+ Response 200 (application/json)

        {
          "collection":
          {
            "version": "1.0",
            "href": "http://www.oneboxtm.com/api-crm/v1.0/",
            "trace_id": "94abc26e-173a-4ab2-a71b-863aed20f656",
            "request_date": "2015-08-05T08:40:51Z",
            "channel_id": "int_channel@oneboxtm.com",
            "hits": 2,
            "parameters":
            {
              "id": "",
              "buyer_id": "",
              "start_date": "",
              "end_date": "",
              "event_id": "",
              "session_id": "",
              "channel_name": "",
              "page": 1,
              "page_size": 10,
              "status": "",
              "passbook":
            },

            "purchases": [
            {
                "order":
                {
                  "id": "XCGDEDFEdZ5",
                  "buyer_id": "joan@gmail.com",
                  "language": "es_ES",
                  "amount": 535.43,
                  "products_number": 3,
                  "status": "OK",
                  "channel": "int_channel@oneboxtm.com",
                  "delivery_method": "EMAIL",
                  "order_date": "2015-08-05T08:40:51Z",
                  "passbook_generated": false,
                  "discount_amount": 23.00,
                  "update_date": "2015-08-05T08:40:51Z"
                },
                "products": [
                  {
                    "id": "439832",
                    "sku": "LATERAL 1",
                    "description": "Tribuna lateral 1a",
                    "taxonomy": "43123",
                    "taxonomy_description": "DEPFUT",
                    "event": "4324",
                    "event_description": "Campeonato de liga 15-16",
                    "session": "5438943",
                    "amount": 125.45,
                    "discount_amount": 00.00,
                    "passbook_generated": false,
                    "update_date": "2015-08-05T08:40:51Z"
                  },
                  {
                    "id": "439831",
                    "sku": "LATERAL 1",
                    "description": "Tribuna lateral 1a",
                    "taxonomy": "43123",
                    "taxonomy_description": "DEPFUT",
                    "event": "4324",
                    "event_description": "Campeonato de liga 15-16",
                    "session": "5438943",
                    "amount": 225.45,
                    "discount_amount": 23.00,
                    "passbook_generated": false,
                    "update_date": "2015-08-05T08:40:51Z"
                  },
                  {
                    "id": "439833",
                    "sku": "GOL NORD",
                    "description": "Tribuna de gol nord.",
                    "taxonomy": "43123",
                    "taxonomy_description": "DEPFUT",
                    "event": "4324",
                    "event_description": "Campeonato de liga 15-16",
                    "session": "5438943",
                    "amount": 25.00,
                    "discount_amount": 00.00,
                    "passbook_generated": false,
                    "update_date": "2015-08-05T08:40:51Z"
                  }
                ]
              }
            ],

            "links": [
              {
                "name": "next_page",
                "prompt": "Next",
                "rel": "next",
                "href": "purchases?page=1",
                "render": "link"
              },
              {
                "name": "previous_page",
                "prompt": "Bext",
                "rel": "back",
                "href": "purchses?page=1",
                "render": "link"
              }
            ]
          }
        }

+ Response 204 (application/json)

+ Response 400 (application/json)

        {
          "error": "Bad request",
          "error_description": "There was a syntax error, check your params request and try it again."
        }

+ Response 401 (application/json)

        {
              "error": "unauthorized",
              "error_description": "Full authentication is required to access this resource"
        }